server:
  port: 0

spring:
  application:
    name: notification-service

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true


