server:
  port: 8765
#  http2:
#    enabled: true
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    key-password: password
#    enabled: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:

          enabled: true
          lower-case-service-id: true

      x-forwarded:
        enabled: true
        for-enabled: true
        proto-enabled: true
        host-append: false
        port-append: false
        proto-append: false

#      httpclient:
#        ssl:
#          use-insecure-trust-manager: true
#
#      routes:
#        - id: grpc
#          uri: lb://control-point-service
#          predicates:
#            - Path=/verification
#            - Method=POST
#          filters:
#            - AddResponseHeader=X-Request-header, header-value


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://host.docker.internal:8761/eureka/}

