server:
  port: 0



spring:
  application:
    name: security-service
  datasource:
    url: jdbc:postgresql://localhost:5432/office-security
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: main_schema

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://host.docker.internal:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    instance-id: security-service-${random.uuid}



grpc:
  server:
    port: 9090

